### ISSUE TITLE
Sponsor links

### ISSUE THREAD

**Issue by marieepicraces** [realbig/RBM_TH_EPIC#135]
The Sponsor links are not showing up on the site now. When I go into the Partner section to add the links to the images, I don't see an option for that now. We'd like our Sponsor or Partner images to be direct links to our sponsors' websites

**Comment by d4mation** [comment]
I went ahead and pushed this one straight to Live as it was a higher priority given the Sponsors weren't showing at all on Live. There was some data migration errors from the old theme to the new one, but I corrected them.

You can add the Links when editing the Sponsors/Partners in the same place as where you dictate whether or not it shows on the Home Page. The option was not working correctly with the data migration either, so I fixed that as well.

![image](https://user-images.githubusercontent.com/7770631/45362443-d654a100-b5a2-11e8-9b00-2079b976ebfd.png)

**Comment by marieepicraces** [comment]
Yet, the links don't seem to work on the privately published page that I've
created. American Home Fitness is the one I've been checking. It works on
our public page but the link doesn't work in the new format, at least, not
on my privately published page.

Can you look at this?

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by d4mation** [comment]
Just pushed a fix for that. I am still finding my way around this code base as well, so thank you for your patience.

**Comment by marieepicraces** [comment]
Great, thanks!

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by marieepicraces** [comment]
The feature that you sent a screen shot for earlier is still not working. I go in to change the slider but the change doesn't "stick" when I update.

**Comment by d4mation** [comment]
I just fixed this as part of #137 since you had reported it there.
